chore: Update ci.yml, cdk unit test, and the pre-commit hook.

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,25 +1,25 @@
-#!/usr/bin/env sh
-. "$(dirname "$0")/_/husky.sh"
+  #!/usr/bin/env sh
+  . "$(dirname "$0")/_/husky.sh"
 
-echo "🔎 Running lint-staged..."
-npx lint-staged
+  echo "🔎 Running lint-staged..."
+  npx lint-staged
 
-if [ $? -ne 0 ]; then
-  echo "❌ Lint-staged failed. Please fix errors before committing."
-  exit 1
-fi
+  if [ $? -ne 0 ]; then
+    echo "❌ Lint-staged failed. Please fix errors before committing."
+    exit 1
+  fi
 
-echo "🧪 Running unit tests…"
-# Passing --bail so Jest stops on the first failure
-npm test -- --bail --silent
-if [ $? -ne 0 ]; then
-  echo "❌ Unit tests failed. Please fix them before committing."
-  exit 1
-fi
+  echo "🧪 Running unit tests…"
+  # Passing --bail so Jest stops on the first failure
+  npm test -- --bail --silent
+  if [ $? -ne 0 ]; then
+    echo "❌ Unit tests failed. Please fix them before committing."
+    exit 1
+  fi
 
-echo "🔨 Running infra unit tests…"
-(cd infra && npm test -- --bail --silent)
-if [ $? -ne 0 ]; then
-  echo "❌ Infra tests failed. Please fix them before committing."
-  exit 1
-fi
+  echo "🔨 Running infra unit tests…"
+  (cd infra && npm ci && npm run build && npm test -- --bail --silent)
+  if [ $? -ne 0 ]; then
+    echo "❌ Infra unit tests failed. Please fix them before committing."
+    exit 1
+  fi
